//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueOper.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueElement
    {
        public int Id_el { get; set; }
        public Nullable<int> Id_q { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_status { get; set; }
        public Nullable<int> Id_oper { get; set; }
        public string Id_window { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Queue Queue { get; set; }
        public virtual Status Status { get; set; }
        public virtual Window_ Window_ { get; set; }
    }
}
