//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueProj.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueElement
    {
        public int Id_el { get; set; }
        public Nullable<int> Id_q { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_status { get; set; }
        public Nullable<int> Id_oper { get; set; }
        public string Id_window { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Queue Queue { get; set; }
        public virtual Status Status { get; set; }
        public virtual Window_ Window_ { get; set; }
    }
}
